name: Deploy Python App to VDS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (just to start workflow, not needed on server)
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VDS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VDS_IP }} >> ~/.ssh/known_hosts

    - name: SSH into VDS and Deploy
      run: |
        ssh ${{ secrets.VDS_USER }}@${{ secrets.VDS_IP }} << 'EOF'
          set -e
    
          APP_DIR="/opt/my-python-app"
          REPO_SSH="git@github.com:Notenlish/hukuksuzlugun-bedeli.git"
    
          if [ -d "$APP_DIR/.git" ]; then
              echo "Repo exists. Fetching latest..."
              cd $APP_DIR
              git fetch origin
              git reset --hard origin/main
          else
              echo "Cloning repo..."
              git clone $REPO_SSH $APP_DIR
          fi
    
          cd $APP_DIR/backend
          pip3 install -r requirements.txt
    
          # Create systemd service if it doesn't exist
          SERVICE_FILE="/etc/systemd/system/myapp.service"
          if [ ! -f "$SERVICE_FILE" ]; then
            echo "Creating systemd service..."
            cat <<EOL > $SERVICE_FILE
    [Unit]
    Description=My Python App
    After=network.target
    
    [Service]
    User=root
    WorkingDirectory=$APP_DIR/backend
    ExecStart=/usr/bin/env uvicorn main:app --host 0.0.0.0 --port 8000
    Restart=always
    
    [Install]
    WantedBy=multi-user.target
    EOL
            systemctl daemon-reexec
            systemctl daemon-reload
            systemctl enable myapp
          fi
    
          systemctl restart myapp
        EOF